import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
test.use({ serviceWorkers: 'allow' });
test('catálogo e mega busca offline; PDF e extrações brutas ficam fora do artefato', async ({ page, context }) => {
  test.setTimeout(120000);
  const root = new URL('../../../', import.meta.url);
  execFileSync('python3',['scripts/preparar_dist.py','--destino','_dist/magias-verificacao','--build','2026092202'],{ cwd:root });
  const build = new URL('../../../_dist/magias-verificacao/', import.meta.url).pathname;
  const arquivos = pasta => readdirSync(pasta,{ withFileTypes:true }).flatMap(e => e.isDirectory() ? arquivos(join(pasta,e.name)) : [join(pasta,e.name)]);
  expect(arquivos(build).filter(p => /\.pdf$/i.test(p))).toEqual([]);
  expect(existsSync(join(build,'reference'))).toBe(false);
  expect(existsSync(join(build,'assets-private'))).toBe(false);
  expect(arquivos(build).some(p => p.includes('phb-spells-raw'))).toBe(false);
  const url = 'http://127.0.0.1:8024/_dist/magias-verificacao/site/';
  await page.goto(url);
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
  await context.setOffline(true);
  await page.reload();
  await page.locator('#menu-todas-magias').click();
  const busca = page.locator('[data-gs="busca"]');
  await expect(busca).toBeVisible();
  await page.locator('[data-gs="origem"]').selectOption('2014-legacy');
  const expected = JSON.parse(readFileSync(new URL('../../../reference/audits/phb-spells-audit.json', import.meta.url))).passes.descriptions.normalized;
  await expect(page.locator('[data-gs="contador"]')).toContainText(`${expected} magias encontradas`);
  await busca.fill('orientacao');
  await expect(page.locator('.spell-result')).toHaveCount(1);
  await expect(page.locator('.spell-result')).toHaveAttribute('data-spell-id','phb-2014-guidance');
});
